### ISSUE TITLE
Pointer concepts

### ISSUE THREAD

**Issue by EvgeniyMsk** [EvgeniyMsk/allocator#3]
Create pointer concepts as a trait classes inherits std::integral_constant. 
Required concepts: single_object_ptr, array_ptr, random_access_ptr, raw_ptr.
Also refactor pointer_casts struct to templated struct with single template parameter. For any casts use pointer_trait<ptr>::rebind as a parameter. 
Provide templated struct pointer_conversion in order to allow a constuction of pointer from pointer with different type and memory size. 
Provide trait to check possibility of pointer conversion.

**Comment by eupp** [comment]
done: 511768d59faa2e4a33fa15a8ac218675dee720a6
